using System;
using ProjectEuler.Problems;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace ProjectEuler.Tests
{
    /// <summary>
    /// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
    /// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    /// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
    /// </summary>
    [TestClass]
    public class Problem2Test
    {

        Problem2 p2;

        [TestInitialize]
        public void TestInit()
        {
            p2 = new Problem1();
        }

        [TestMethod]
        public void FindingSumOf2()
        {
            int expected = 2;
            long actual = p2.FindSum(10);

            Assert.AreEqual(expected, actual);
        }
    }
}
